import 'package:ehap_s_application2/core/app_export.dart';import 'package:ehap_s_application2/core/utils/validation_functions.dart';import 'package:ehap_s_application2/widgets/app_bar/appbar_image.dart';import 'package:ehap_s_application2/widgets/app_bar/appbar_subtitle.dart';import 'package:ehap_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:ehap_s_application2/widgets/custom_button.dart';import 'package:ehap_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class ResetPasswordThreeScreen extends StatelessWidget {TextEditingController newpasswordController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(99), leadingWidth: 44, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftGray900, margin: getMargin(left: 20, top: 45, bottom: 30), onTap: () => onTapArrowleft6(context)), centerTitle: true, title: AppbarSubtitle(text: "Create New Password"), styleType: Style.bgFillGray50), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: getPadding(left: 20, top: 32, right: 20, bottom: 32), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle100320x350, height: getVerticalSize(320), width: getHorizontalSize(350), radius: BorderRadius.circular(getHorizontalSize(10))), Padding(padding: getPadding(top: 19), child: Text("Create New Password", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtCairoRegular18)), Container(width: getHorizontalSize(317), margin: getMargin(left: 16, top: 6, right: 15), child: Text("Create Strong Password To Protect it from hacking", maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtCairoRegular16Black9007e)), CustomTextFormField(focusNode: FocusNode(), controller: newpasswordController, hintText: "New Password", margin: getMargin(top: 22), variant: TextFormFieldVariant.OutlineGray50004, padding: TextFormFieldPadding.PaddingAll11, fontStyle: TextFormFieldFontStyle.CairoRegular15Gray50004, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, isObscureText: true), CustomButton(height: getVerticalSize(50), text: "Create Password", margin: getMargin(top: 22, bottom: 5), variant: ButtonVariant.FillIndigo90001, padding: ButtonPadding.PaddingAll10, fontStyle: ButtonFontStyle.CairoBold16, onTap: () => onTapCreatepassword(context))]))))); } 
onTapCreatepassword(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginScreen); } 
onTapArrowleft6(BuildContext context) { Navigator.pop(context); } 
 }
