import 'package:ehap_s_application2/core/app_export.dart';import 'package:ehap_s_application2/widgets/custom_button.dart';import 'package:ehap_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class LangugeModeCountryScreen extends StatelessWidget {TextEditingController languageController = TextEditingController();

TextEditingController group323Controller = TextEditingController();

TextEditingController languageOneController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: getPadding(left: 15, top: 90, right: 15), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgGroup38009, height: getSize(131), width: getSize(131)), Padding(padding: getPadding(top: 8), child: Text("Welcome To Suiiz", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtCairoSemiBold24)), CustomTextFormField(focusNode: FocusNode(), controller: languageController, hintText: "Select Language", margin: getMargin(top: 38), variant: TextFormFieldVariant.FillGray100, fontStyle: TextFormFieldFontStyle.CairoMedium15, suffix: Container(margin: getMargin(left: 30, top: 22, right: 20, bottom: 22), decoration: BoxDecoration(color: ColorConstant.black900, borderRadius: BorderRadius.circular(getHorizontalSize(1))), child: CustomImageView(svgPath: ImageConstant.imgPolygon1)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(55))), CustomTextFormField(focusNode: FocusNode(), controller: group323Controller, hintText: "country", margin: getMargin(top: 16), variant: TextFormFieldVariant.FillGray100, fontStyle: TextFormFieldFontStyle.CairoMedium15, suffix: Container(margin: getMargin(left: 30, top: 22, right: 20, bottom: 22), decoration: BoxDecoration(color: ColorConstant.black900, borderRadius: BorderRadius.circular(getHorizontalSize(1))), child: CustomImageView(svgPath: ImageConstant.imgPolygon1)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(55))), CustomTextFormField(focusNode: FocusNode(), controller: languageOneController, hintText: "mode ", margin: getMargin(top: 16), variant: TextFormFieldVariant.FillGray100, fontStyle: TextFormFieldFontStyle.CairoMedium15, textInputAction: TextInputAction.done, suffix: Container(margin: getMargin(left: 30, top: 22, right: 20, bottom: 22), decoration: BoxDecoration(color: ColorConstant.black900, borderRadius: BorderRadius.circular(getHorizontalSize(1))), child: CustomImageView(svgPath: ImageConstant.imgPolygon1)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(55))), CustomButton(height: getVerticalSize(55), text: "Strat", margin: getMargin(top: 24, bottom: 5), variant: ButtonVariant.FillIndigo900, padding: ButtonPadding.PaddingAll10, fontStyle: ButtonFontStyle.CairoSemiBold18, onTap: () => onTapStrat(context))])))); } 
onTapStrat(BuildContext context) { Navigator.pushNamed(context, AppRoutes.onBoardingScreenOneScreen); } 
 }
